version: '3.8'

volumes:
  wp:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/jukim2/data/wordpress
  db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/jukim2/data/mariaDB
    
networks:
  inception:

services:
  nginx:
    image: nginx
    build: srcs/nginx
    ports: 
      - "443:443"
    volumes:
      - "wp:/var/www/html"
    networks:
      - inception
    depends_on:
      - wordpress

  wordpress:
    image: wordpress
    build: srcs/wordpress
    expose:
      - 9000
    volumes:
      - "wp:/var/www/html"
    networks:
      - inception
    env_file:
      - .env
    depends_on:
      - mariadb

  mariadb:
    image: mariadb
    build: srcs/mariaDB
    volumes:
      - "db:/var/lib/mysql"
    expose:
      - 3306
    env_file:
      - .env
    networks:
      - inception
