#mairaDB
FROM debian:bullseye

COPY generateDB.sh .

# Install PHP and wget
RUN apt-get update -y && \
    apt-get upgrade -y && \
    apt-get install -y curl && \
    apt-get install -y sudo && \
    apt-get install -y mariadb-server && \
    chmod +x generateDB.sh

COPY my.cnf /etc/mysql/my.cnf
COPY 50-server.cnf etc/mysql/mariadb.conf.d/50-server.cnf

ENTRYPOINT ["sh", "generateDB.sh"]