#nginx
FROM debian:bullseye

RUN apt-get update -y && \
    apt-get upgrade -y && \
    apt-get install -y nginx && \
    apt-get install -y openssl && \
    mkdir -p /etc/nginx/ssl && \
    openssl req -new -x509 -newkey rsa:2048 -nodes -keyout server.key -out server.crt -days 365 -subj "/C=KR/ST=Seoul/L=Seoul/O=My Company/OU=IT/CN=localhost" && \
    mv server.key /etc/nginx/ssl && \
    mv server.crt /etc/nginx/ssl
    
COPY nginx.conf /etc/nginx/nginx.conf

# Start Nginx in the foreground
ENTRYPOINT ["nginx", "-g", "daemon off;"]